# Generated by Django 3.1 on 2020-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='All', max_length=1),
        ),
    ]
