# Generated by Django 3.1 on 2020-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default=3, max_length=1),
        ),
    ]
