# Generated by Django 3.1 on 2020-09-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
