# Generated by Django 3.1 on 2020-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
