# Generated by Django 3.1 on 2020-09-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='postcode',
        ),
    ]
